Feat/create providers
bimartinez/IIC3143-Naranjus-backend pull request #12
Opened 2021-06-21 02:48 UTC by Mnfriedl

Se creó el modelo para `Provider`. Están disponibles los _endpoints_ para crear, modificar, eliminar un `Provider`, y además un _endpoint_ para obtener una lista de todos los `Provider`'s.

El detalle de la ruta de los _endpoints_ está en _Postman_.

2021-06-21 02:56 UTC, Mnfriedl commented
![](https://github.trello.services/images/mini-trello-icon.png) [R17 Ingreso de proveedores](https://trello.com/c/o2qA5gzE/24-r17-ingreso-de-proveedores)

2021-06-22 19:31 UTC, fgbruna requested changes

2021-06-22 19:31 UTC, fgbruna commented on providers/admin.py
> +from .models import Provider
lets stay consistent and use `providers.models` like we did in the users app

2021-06-22 19:31 UTC, fgbruna commented on providers/api.py
> +from .serializers import ProviderSerializer
`providers.serializers`

2021-06-22 19:31 UTC, fgbruna commented on providers/serializers.py
> +from .models import Provider
`providers.models`

2021-06-22 19:31 UTC, fgbruna commented on providers/urls.py
> +from . import api
`providers.api`

2021-06-26 00:51 UTC, fgbruna approved these changes

2021-06-26 00:51 UTC, merged