Feat/visitor
bimartinez/IIC3143-Naranjus-backend pull request #14
Opened 2021-07-03 05:48 UTC by Mnfriedl

Modelo y rutas para crear/modificar/eliminar y lista de visitantes.

Las rutas están en Postman.

2021-07-03 21:45 UTC, bimartinez requested changes

2021-07-03 21:45 UTC, bimartinez commented on entrance_control/urls.py
> +    path('', include('providers.urls'), name='providers'),
Why here we don't have this?
```suggestion
    path('providers/', include('providers.urls'), name='providers'),
```

2021-07-03 21:45 UTC, bimartinez commented on visitors/models.py
> +    rut = models.CharField(max_length=10)  # 01.234.567-9
I think the format is without separating dots
```suggestion
    rut = models.CharField(max_length=10)  # 01234567-9
```

2021-07-03 21:45 UTC, bimartinez commented on visitors/serializers.py
> +        fields = [
We should use single quotes pls

2021-07-03 21:45 UTC, bimartinez commented on visitors/serializers.py
> +        fields = [
Same here, single quotes pls

2021-07-03 21:45 UTC, bimartinez commented on visitors/urls.py
> +    path("visitors/", api.VisitorsList.as_view()),
Here you have to remove the `visitors/` prefix and add it on the main `urls.py` file, also use single quotes

2021-07-03 21:45 UTC, bimartinez commented on entrance_control/urls.py
> +    path('', include('visitors.urls'), name='visitors'),
Same here
```suggestion
    path('visitors/', include('visitors.urls'), name='visitors'),
```

2021-07-03 23:12 UTC, fgbruna approved these changes

2021-07-04 01:27 UTC, bimartinez requested changes

2021-07-04 01:27 UTC, bimartinez commented on visitors/models.py
> +        return f"{self.name} {self.lastname}"
Use single quotes please

2021-07-04 02:34 UTC, bimartinez approved these changes

2021-07-04 02:36 UTC, merged